import React from 'react';

const word_html = (
    <div class="Section0" style="layout-grid:15.6000pt;"><p class="MsoNormal" align="center" style="margin-left:-9.9500pt;mso-para-margin-left:-0.9500gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;text-align:center;line-height:150%;"><b style="mso-bidi-font-weight:normal"><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
line-height:150%;mso-ansi-font-weight:bold;font-size:16.0000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">北京工业大学耿丹学院</font></span></b><b style="mso-bidi-font-weight:normal"><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
line-height:150%;mso-ansi-font-weight:bold;font-size:16.0000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><b style="mso-bidi-font-weight:normal"><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
line-height:150%;mso-ansi-font-weight:bold;font-size:16.0000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">毕业设计（论文）选题申报表</font></span></b><b style="mso-bidi-font-weight:normal"><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
line-height:150%;mso-ansi-font-weight:bold;font-size:16.0000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p><table class="MsoNormalTable" border="1" cellspacing="0" style="border-collapse:collapse;width:417.3500pt;margin-left:4.4000pt;
mso-table-layout-alt:fixed;border:none;mso-border-left-alt:0.5000pt solid windowtext;
mso-border-top-alt:0.5000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;mso-border-bottom-alt:0.5000pt solid windowtext;
mso-border-insideh:0.5000pt solid windowtext;mso-border-insidev:0.5000pt solid windowtext;mso-padding-alt:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;"><tbody><tr style="height:22.8000pt;page-break-inside:avoid;"><td width="111" valign="center" style="width:55.9000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:1.0000pt solid windowtext;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">申报题目</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="460" valign="center" colspan="4" style="width:230.4500pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:1.0000pt solid windowtext;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(12,12,12);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">耿丹学院毕业设计管理平台的设计与实现</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="141" valign="center" colspan="3" style="width:70.7500pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:1.0000pt solid windowtext;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">类型</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="120" valign="center" style="width:60.2500pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:1.0000pt solid windowtext;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;">B</span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="Times New Roman">X</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td></tr><tr style="height:23.0500pt;"><td width="111" valign="center" style="width:55.9000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">来源</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="348" valign="center" colspan="3" style="width:174.3500pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="Times New Roman">E</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="112" valign="center" style="width:56.1000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">毕设地点</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="262" valign="center" colspan="4" style="width:131.0000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">北京工业大学耿丹学院</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td></tr><tr style="height:22.6000pt;page-break-inside:avoid;"><td width="111" valign="center" style="width:55.9000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">导师姓名</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="142" valign="center" style="width:71.2000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">方红琴</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="93" valign="center" style="width:46.8000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">性别</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="112" valign="center" style="width:56.3500pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">女</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="112" valign="center" style="width:56.1000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:1.0000pt solid windowtext;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">年龄</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="77" valign="center" style="width:38.5000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:1.0000pt solid windowtext;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="Times New Roman">47</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="64" valign="center" colspan="2" style="width:32.2500pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:1.0000pt solid windowtext;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">职称</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="120" valign="center" style="width:60.2500pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:1.0000pt solid windowtext;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">副教授</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td></tr><tr style="height:30.7000pt;page-break-inside:avoid;"><td width="111" valign="center" style="width:55.9000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:none;
mso-border-bottom-alt:none;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">所在单位</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="236" valign="center" colspan="2" style="width:118.0000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:none;
mso-border-bottom-alt:none;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">北京工业大学耿丹学院</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="112" valign="center" style="width:56.3500pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:none;
mso-border-bottom-alt:none;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">所学专业</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="112" valign="center" style="width:56.1000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:none;
mso-border-bottom-alt:none;"><p class="MsoNormal" align="center" style="text-autospace:ideograph-numeric;mso-pagination:none;text-align:center;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">计算机科学与技术</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="120" valign="center" colspan="2" style="width:60.0000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:none;
mso-border-bottom-alt:none;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">联系电话</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td><td width="142" valign="center" colspan="2" style="width:71.0000pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:none;
mso-border-bottom-alt:none;"><p class="MsoNormal" align="center" style="text-align:center;line-height:150%;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="Times New Roman">15810989589</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td></tr><tr style="height:83.7000pt;"><td width="834" valign="top" colspan="9" style="width:417.3500pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:1.0000pt solid windowtext;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" style="margin-left:5.4000pt;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">课题介绍：</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-top:4.6500pt;margin-bottom:4.6500pt;mso-para-margin-top:0.3000gd;
mso-para-margin-bottom:0.3000gd;text-indent:5.2500pt;mso-char-indent-count:0.5000;
line-height:16.0000pt;mso-line-height-rule:exactly;"><b style="mso-bidi-font-weight:normal"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
mso-ansi-font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">主要内容：</font></span></b><b style="mso-bidi-font-weight:normal"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
mso-ansi-font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p><p class="MsoNormal" style="margin-left:1.7000pt;text-indent:24.6500pt;mso-char-indent-count:2.3500;
line-height:16.0000pt;mso-line-height-rule:exactly;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:150%;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">本课题根据</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">北京工业大学耿丹学院的毕业设计（论文）管理流程</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:150%;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">完成毕业设计管理系统</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">，使学生能够了解毕业设计的流程，提高各学生、教师、二级学院教学秘书、教务办公室各部分之间的交流效率，使每一步流程的管理得到系统的监督和审查，能够更有条理的进行文档的管理以及设置文档权限，系统的、完整的包含所有毕业设计（论文）的执行流程</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:150%;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">，</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">提高管理质量。</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:150%;color:rgb(12,12,12);
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">耿丹学院</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">毕业设计（论文）管理</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:150%;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">系统主要包括以下内容。</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:150%;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:1.7000pt;text-indent:24.6500pt;mso-char-indent-count:2.3500;
line-height:16.0000pt;mso-line-height-rule:exactly;mso-list:l0 level1 lfo1;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><span style="mso-list:Ignore;">1、<span>&nbsp;</span></span></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">教师、学生身份的用户第一次登录后对自我信息的补全，教务办公室</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">、二级学院教学秘书可以依据相应权限对</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">用户的</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">进行管理</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:1.7000pt;mso-para-margin-left:0.0000gd;text-indent:24.6500pt;
mso-char-indent-count:2.3500;line-height:16.0000pt;mso-line-height-rule:exactly;
mso-list:l0 level1 lfo1;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><span style="mso-list:Ignore;">2、<span>&nbsp;</span></span></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">学</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">生</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">以及导师在毕业设计开始前的互选。学生可以</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">查看可选导师的信息以及</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">进行</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">志愿导师的填写、教师查看学生的志愿情况并且做出选择的。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:1.7000pt;mso-para-margin-left:0.0000gd;text-indent:24.6500pt;
mso-char-indent-count:2.3500;line-height:16.0000pt;mso-line-height-rule:exactly;
mso-list:l0 level1 lfo1;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><span style="mso-list:Ignore;">3、<span>&nbsp;</span></span></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">信息的提醒与通知，比如教师可以向自己负责的学生下达填写开</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">毕业设计流程中某一项的</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">消息，学生可以在下发的消息中进行</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">提交</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">和留言。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:1.7000pt;mso-para-margin-left:0.0000gd;text-indent:24.6500pt;
mso-char-indent-count:2.3500;line-height:16.0000pt;mso-line-height-rule:exactly;
mso-list:l0 level1 lfo1;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><span style="mso-list:Ignore;">4、<span>&nbsp;</span></span></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">拥有不同权限的用户可以对文档库中不同权限的文档进行上传、下载、删除</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">等功能，实现文档管理。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:1.7000pt;mso-para-margin-left:0.0000gd;text-indent:24.6500pt;
mso-char-indent-count:2.3500;line-height:16.0000pt;mso-line-height-rule:exactly;
mso-list:l0 level1 lfo1;"><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><span style="mso-list:Ignore;">5、<span>&nbsp;</span></span></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">学生可以直接填写页面内的表单，系统会提取填写内容生成规定格式的文件，避免填写格式不规范的问题。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:1.7000pt;text-indent:24.6500pt;mso-char-indent-count:2.3500;
line-height:16.0000pt;mso-line-height-rule:exactly;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal" style="margin-top:4.6500pt;margin-bottom:4.6500pt;mso-para-margin-top:0.3000gd;
mso-para-margin-bottom:0.3000gd;text-indent:5.2500pt;mso-char-indent-count:0.5000;
line-height:16.0000pt;mso-line-height-rule:exactly;"><b style="mso-bidi-font-weight:normal"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);mso-ansi-font-weight:bold;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">现有条件：</font></span></b><b style="mso-bidi-font-weight:normal"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);mso-ansi-font-weight:bold;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p><p class="MsoNormal" style="margin-left:5.4000pt;text-indent:21.0000pt;line-height:16.0000pt;
mso-line-height-rule:exactly;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">具备完成毕业设计的软硬件条件。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-top:4.6500pt;margin-bottom:4.6500pt;mso-para-margin-top:0.3000gd;
mso-para-margin-bottom:0.3000gd;text-indent:5.2500pt;mso-char-indent-count:0.5000;
line-height:16.0000pt;mso-line-height-rule:exactly;"><b style="mso-bidi-font-weight:normal"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);mso-ansi-font-weight:bold;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">实践安排：</font></span></b><b style="mso-bidi-font-weight:normal"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);mso-ansi-font-weight:bold;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p><p class="MsoNormal" style="margin-left:5.4000pt;text-indent:21.0000pt;line-height:16.0000pt;
mso-line-height-rule:exactly;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">1<font face="宋体">、通过各种渠道对</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:150%;color:rgb(0,0,0);
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">毕业设计（论文）管理系统</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">进行需求分析，形成需求分析报告。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:5.4000pt;text-indent:21.0000pt;line-height:16.0000pt;
mso-line-height-rule:exactly;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">2<font face="宋体">、根据需求分析报告完成系统设计和详细设计。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:5.4000pt;text-indent:21.0000pt;line-height:16.0000pt;
mso-line-height-rule:exactly;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">3<font face="宋体">、完成系统编码。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:5.4000pt;text-indent:21.0000pt;line-height:16.0000pt;
mso-line-height-rule:exactly;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">4<font face="宋体">、对系统进行测试。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:5.4000pt;text-indent:21.0000pt;line-height:16.0000pt;
mso-line-height-rule:exactly;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">5<font face="宋体">、根据各个阶段的具体情况完成毕业论文。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-top:4.6500pt;margin-bottom:4.6500pt;mso-para-margin-top:0.3000gd;
mso-para-margin-bottom:0.3000gd;text-indent:5.2500pt;mso-char-indent-count:0.5000;
line-height:16.0000pt;mso-line-height-rule:exactly;"><b style="mso-bidi-font-weight:normal"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);mso-ansi-font-weight:bold;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">预期成果：</font></span></b><b style="mso-bidi-font-weight:normal"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);mso-ansi-font-weight:bold;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p><p class="MsoNormal" style="margin-left:5.4000pt;text-indent:21.0000pt;line-height:16.0000pt;
mso-line-height-rule:exactly;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">1<font face="宋体">、具有一定实用价值的</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:150%;color:rgb(0,0,0);
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">学生家校联系平台</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">，能实现</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:150%;color:rgb(0,0,0);
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">毕业设计（论文）管理系统</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">的基本功能。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:5.4000pt;text-indent:21.0000pt;line-height:16.0000pt;
mso-line-height-rule:exactly;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">2<font face="宋体">、根据毕业设计的实际情况和毕业设计规范要求完成的毕业论文。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-top:4.6500pt;margin-bottom:4.6500pt;mso-para-margin-top:0.3000gd;
mso-para-margin-bottom:0.3000gd;text-indent:5.2500pt;mso-char-indent-count:0.5000;
line-height:16.0000pt;mso-line-height-rule:exactly;"><b style="mso-bidi-font-weight:normal"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);mso-ansi-font-weight:bold;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">表现形式：</font></span></b><b style="mso-bidi-font-weight:normal"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);mso-ansi-font-weight:bold;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p><p class="MsoNormal" style="margin-left:5.4000pt;text-indent:21.0000pt;line-height:16.0000pt;
mso-line-height-rule:exactly;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">1<font face="宋体">、能运行的具有实用价值的</font></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';line-height:150%;color:rgb(0,0,0);
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">毕业设计（论文）管理系统</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:5.4000pt;text-indent:21.0000pt;line-height:16.0000pt;
mso-line-height-rule:exactly;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">2<font face="宋体">、符合规范要求的毕业论文。</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;line-height:150%;
color:rgb(0,0,0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:5.4000pt;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;color:rgb(0,0,0);
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal" style="margin-left:5.4000pt;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;color:rgb(0,0,0);
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">申报人签名：</font> <span style="mso-spacerun:'yes';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';color:rgb(0,0,0);font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><span style="font-family:'Times New Roman';mso-spacerun:'yes';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;color:rgb(0,0,0);
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><span style="mso-spacerun:'yes';">&nbsp;</span><font face="宋体">日期：</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td></tr><tr style="height:51.7000pt;"><td width="834" valign="bottom" colspan="9" style="width:417.3500pt;padding:0.0000pt 5.4000pt 0.0000pt 5.4000pt ;border-left:1.0000pt solid windowtext;
mso-border-left-alt:0.5000pt solid windowtext;border-right:1.0000pt solid windowtext;mso-border-right-alt:0.5000pt solid windowtext;
border-top:none;mso-border-top-alt:0.5000pt solid windowtext;border-bottom:1.0000pt solid windowtext;
mso-border-bottom-alt:0.5000pt solid windowtext;"><p class="MsoNormal" style="line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal" style="margin-left:5.4000pt;line-height:150%;"><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><font face="宋体">毕业设计（论文）领导小组签字：</font> <span style="mso-spacerun:'yes';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><font face="宋体">日期：</font></span><span style="font-family:'Times New Roman';mso-fareast-font-family:宋体;font-size:10.5000pt;
mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></td></tr></tbody></table><p class="MsoNormal" style="line-height:150%;"><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal" style="line-height:150%;"><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">填表说明：</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="line-height:150%;"><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">1．每项内容教师都必须认真填写。</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="line-height:150%;"><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">2．课题来源：A—校内教研基金；B—校内科研基金；C—企事业单位合作课题；D—政府部门支持课题；E—教师自拟课题；F—其他。</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="line-height:150%;"><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">3．课题类型：（1）A—工程设计；B—技术开发；C—软件工程；D—理论研究；E</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">—</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">应用研究。</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="text-indent:10.5000pt;mso-char-indent-count:1.0000;line-height:150%;"><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><font face="宋体">（</font><font face="宋体">2）X—真实课题；Y—模拟课题；Z—虚拟课题；（1）、（2）均要填，如AY。</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p></div>
)

const Test = () => {
    return (
        <div>
            {word_html}
        </div>
    );
}

export default Test;
